import {useEffect,useState} from 'react';
import {Handshake,ImagePlus,Plus,Trash2} from 'lucide-react';
import toast from 'react-hot-toast';
import {apiUrl} from '../lib/api.js';

const partnerImage=item=>item?.imageId?apiUrl('/api/co-partner-media/'+item.imageId):item?.image||'';

export default function CoPartnersAdmin({request}){
  const[items,setItems]=useState([]),[edit,setEdit]=useState(null),[imageFile,setImageFile]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[revision,setRevision]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);request('/api/admin/co-partners').then(data=>{if(active){setItems(data.items||[]);setError('')}}).catch(err=>{if(active){setError(err.message);toast.error(err.message)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[request,revision]);
  const open=item=>{setEdit({...item});setImageFile(null);setError('');setFields({});};
  const save=async event=>{event.preventDefault();if(busy)return;setBusy(true);setError('');setFields({});try{const data=new FormData();data.append('data',JSON.stringify(edit));if(imageFile)data.append('image',imageFile);await request('/api/admin/co-partners'+(edit.id?'/'+edit.id:''),{method:edit.id?'PUT':'POST',body:data});toast.success(edit.id?'Industry associate updated.':'Industry associate added.');setEdit(null);setImageFile(null);setRevision(value=>value+1)}catch(err){setError(err.message);setFields(err.fields||{});toast.error(err.message)}finally{setBusy(false)}};
  const remove=async item=>{if(!confirm(`Delete industry associate “${item.title}”?`))return;setBusy(true);try{await request('/api/admin/co-partners/'+item.id,{method:'DELETE'});toast.success('Industry associate deleted.');setRevision(value=>value+1)}catch(err){toast.error(err.message)}finally{setBusy(false)}};
  const update=(key,value)=>setEdit(item=>({...item,[key]:value}));
  const chooseImage=event=>{const file=event.target.files?.[0];if(!file)return;if(file.size>8*1024*1024||!['image/jpeg','image/png','image/webp'].includes(file.type)){setFields(value=>({...value,image:'Choose a JPEG, PNG or WebP image no larger than 8 MB.'}));event.target.value='';return;}setImageFile(file);setFields(value=>({...value,image:''}));};
  if(edit)return <section className="admin-resource-page"><div className="Properties-admin-header"><div><p className="eyebrow">INDUSTRY ASSOCIATES</p><h1 className="title">{edit.id?'Edit Industry Associate':'Add Industry Associate'}</h1><p>The image, title and description appear in the Our Industry Associates section.</p></div><button className="Properties-button secondary" type="button" onClick={()=>setEdit(null)}>Back to Industry Associates</button></div><form className="admin-resource-form" onSubmit={save}><div className="Properties-form-grid"><label>Title<input value={edit.title} maxLength="120" onChange={event=>update('title',event.target.value)}/>{fields.title&&<small>{fields.title}</small>}</label><label>Display order<input type="number" min="0" max="9999" value={edit.displayOrder} onChange={event=>update('displayOrder',Number(event.target.value))}/>{fields.displayOrder&&<small>{fields.displayOrder}</small>}</label><label className="md:col-span-2">Description<textarea rows="4" maxLength="500" value={edit.description} onChange={event=>update('description',event.target.value)}/>{fields.description&&<small>{fields.description}</small>}</label><div className="admin-cover-upload md:col-span-2"><label>Industry associate image {edit.id&&<span className="Properties-optional">(upload only to replace)</span>}<span className="admin-file-picker"><ImagePlus size={18}/>{edit.id?'Replace image':'Choose image'}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={chooseImage}/></span></label><p>JPEG, PNG or WebP, up to 8 MB.</p>{fields.image&&<small>{fields.image}</small>}{imageFile?<div className="admin-selected-image"><span>{imageFile.name}</span><button type="button" onClick={()=>setImageFile(null)}>Remove selection</button></div>:partnerImage(edit)&&<div className="admin-cover-preview"><img src={partnerImage(edit)} alt={edit.title||'Current industry associate'}/></div>}</div></div>{error&&<p className="Properties-error">{error}</p>}<button className="Properties-button" disabled={busy}>{busy?'Saving…':'Save Industry Associate'}</button></form></section>;
  return <section className="admin-resource-page"><div className="Properties-admin-header"><div><p className="eyebrow">PRISM ADMIN</p><h1 className="title">Industry Associates</h1><p>Manage the associates displayed on the Industry Associates page.</p></div><button className="Properties-button" onClick={()=>open({title:'',description:'',displayOrder:items.length})}><Plus size={17}/>Add Industry Associate</button></div>{loading?<p role="status">Loading industry associates…</p>:error?<p className="Properties-error">{error}</p>:!items.length?<div className="Properties-empty"><Handshake size={38}/><p>No industry associates have been added.</p></div>:<div className="admin-partner-grid">{items.map(item=><article key={item.id}><img src={partnerImage(item)} alt={item.title}/><div><span>Display order {item.displayOrder}</span><h2>{item.title}</h2><p>{item.description||'No description added.'}</p><div className="Properties-actions"><button className="Properties-button secondary" onClick={()=>open(item)}>Edit</button><button className="Properties-button Properties-danger" disabled={busy} onClick={()=>remove(item)}><Trash2 size={15}/>Delete</button></div></div></article>)}</div>}</section>;
}
