import PrismSectionHeading,{SectionSubtitle} from './SectionHeading';
import {useEffect} from 'react';
import {Link} from 'react-router-dom';
import './events-awards.css';
import {Award,Handshake,Users} from 'lucide-react';

function SectionHeading({eyebrow,title,text}){return <div className="mx-auto max-w-4xl text-center"><p className="section-kicker">{eyebrow}</p><PrismSectionHeading as="h2" className="section-heading">{title}</PrismSectionHeading>{text&&<SectionSubtitle className="mx-auto mt-5 max-w-3xl leading-8 text-slate-600">{text}</SectionSubtitle>}</div>}

export default function EventsAwardsPage(){useEffect(()=>{const previousTitle=document.title;const description='Prism Edu Consultancy presents the Principals and School Leadership Award, celebrating excellence and connecting education stakeholders.';document.title='Principals and School Leadership Award | Prism Edu Consultancy';const selectors=['meta[name="description"]','meta[property="og:title"]','meta[property="og:description"]'];const previous=selectors.map(selector=>{const element=document.querySelector(selector);return element?{element,content:element.getAttribute('content')}:{element:null,content:null}});const values=[description,'Principals and School Leadership Award | Prism Edu Consultancy',description];previous.forEach((item,index)=>item.element?.setAttribute('content',values[index]));return()=>{document.title=previousTitle;previous.forEach(item=>item.element&&item.element.setAttribute('content',item.content||''))}},[]);return <div className="events-awards-page">
  <section className="events-awards-hero"><div className="wrap events-hero-grid"><div><p className="section-kicker">PRISM EDU CONSULTANCY PRESENTS</p><PrismSectionHeading as="h1">Principals and School Leadership Award</PrismSectionHeading><SectionSubtitle className="events-tagline">Celebrating Excellence <span>•</span> Connecting Education</SectionSubtitle><p className="mt-5 max-w-2xl leading-8 events-hero-description">A professional platform created to honour the valuable contributions of principals, school leadership teams and educational institutions while connecting stakeholders working for the progress of education.</p><div className="mt-6 flex flex-wrap gap-3">{[[Award,'Showcase Good Practices'],[Users,'Meet Education Leaders'],[Handshake,'Build Meaningful Networks']].map(([Icon,text])=><span className="event-point" key={text}><Icon size={17}/>{text}</span>)}</div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link className="btn" to="/contact?enquiry=events-awards">Register Your Interest</Link></div></div><figure className="events-hero-visual"><img src="/images/events-awards/principals-education-leaders-invitation.jpeg" alt="Prism Edu Consultancy Principals and School Leadership Award" width="1024" height="1536" fetchPriority="high" loading="eager"/><figcaption>Principals and School Leadership Award — celebrating excellence and connecting education.</figcaption></figure></div></section>
  <section className="events-information py-16 md:py-24"><div className="wrap grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><div><PrismSectionHeading as="h2" className="section-heading">Upcoming Event</PrismSectionHeading><SectionSubtitle className="mt-5 leading-7 text-slate-600">Event date and venue details will be announced in the coming days.</SectionSubtitle></div><dl className="event-info-panel">{[['Event','Principals and School Leadership Award'],['Organised by','Prism Edu Consultancy'],['Participants','Principals, Education Leaders and Directors'],['Date','To Be Announced'],['Venue','To Be Announced'],['Registration','Expression of Interest Open']].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></div></section>
  <section className="recognition-video py-16 md:py-24"><div className="wrap"><SectionHeading eyebrow="EVENT MEDIA" title="Recognition Moments" text="A dedicated event video will appear here once the approved video file is available in the project."/><div className="video-placeholder" role="img" aria-label="Event video awaiting approved media"><Award size={52}/><p>Approved event video to be added</p><small>No unavailable or unverified media is presented.</small></div></div></section>
  <section className="why-event-platform py-16 md:py-20"><div className="wrap grid items-center gap-8 md:grid-cols-[180px_1fr]"><img src="/images/events-awards/prism-event-logo.jpg" alt="Prism Edu Consultancy logo" width="180" height="180" loading="lazy"/><div><p className="section-kicker">WHY PRISM CREATES THIS PLATFORM</p><PrismSectionHeading as="h2" className="section-heading">Stronger connections for stronger schools</PrismSectionHeading><SectionSubtitle className="mt-5 max-w-3xl leading-8 text-slate-600">Prism Edu Consultancy aims to connect education stakeholders, understand institutional requirements, support professional collaboration and encourage the sharing of practical ideas for stronger schools.</SectionSubtitle></div></div></section>
  <section className="events-final-cta"><div className="wrap text-center"><PrismSectionHeading as="h2">Be Part of the Education Network</PrismSectionHeading><SectionSubtitle>Join schools, principals, educators, service providers and other stakeholders in a platform designed for recognition, interaction and meaningful collaboration.</SectionSubtitle><div><Link className="btn" to="/contact?enquiry=events-awards">Register Your Interest</Link><Link className="cta-outline" to="/contact">Contact Prism Education</Link><Link className="cta-outline" to="/contact?enquiry=consultation">Request Consultation</Link></div></div></section>
</div>}
