import {useEffect,useState} from 'react';
import {ExternalLink,Plus,Trash2} from 'lucide-react';
import toast from 'react-hot-toast';

const blank={type:'Blogs',title:'',description:'',content:'',url:'',image:'',category:'',date:new Date().toISOString().slice(0,10),author:'',status:'Draft',featured:false,webinarStatus:''};

export default function ResourceAdmin({request}){
  const[items,setItems]=useState([]),[edit,setEdit]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fields,setFields]=useState({}),[revision,setRevision]=useState(0);
  useEffect(()=>{let active=true;setLoading(true);request('/api/admin/resources').then(data=>{if(active){setItems(data.items);setError('')}}).catch(e=>{if(active){setError(e.message);toast.error(e.message)}}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[request,revision]);
  const save=async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');setFields({});try{const url='/api/admin/resources'+(edit.id?'/'+edit.id:'');await request(url,{method:edit.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});toast.success(edit.id?'Resource updated.':'Resource added.');setEdit(null);setRevision(x=>x+1)}catch(err){setError(err.message);setFields(err.fields||{});toast.error(err.message)}finally{setBusy(false)}};
  const remove=async item=>{if(!confirm(`Delete “${item.title}”?`))return;setBusy(true);try{await request('/api/admin/resources/'+item.id,{method:'DELETE'});toast.success('Resource deleted.');setRevision(x=>x+1)}catch(err){toast.error(err.message)}finally{setBusy(false)}};
  const update=(key,value)=>setEdit(item=>({...item,[key]:value}));
  if(edit)return <section className="admin-resource-page"><div className="Properties-admin-header"><div><p className="eyebrow">KNOWLEDGE CENTER</p><h1 className="title">{edit.id?'Edit Resource':'Add Resource'}</h1></div><button className="Properties-button secondary" type="button" onClick={()=>setEdit(null)}>Back to Resources</button></div><form className="admin-resource-form" onSubmit={save}><div className="Properties-form-grid"><label>Resource type<select value={edit.type} onChange={e=>update('type',e.target.value)}><option>Blogs</option><option>Webinars</option><option>Videos</option></select>{fields.type&&<small>{fields.type}</small>}</label><label>Title<input value={edit.title} onChange={e=>update('title',e.target.value)}/>{fields.title&&<small>{fields.title}</small>}</label><label>Category<input value={edit.category} onChange={e=>update('category',e.target.value)} placeholder="Optional category"/></label><label>Publish date<input type="date" value={edit.date} onChange={e=>update('date',e.target.value)}/>{fields.date&&<small>{fields.date}</small>}</label><label>Author<input value={edit.author} onChange={e=>update('author',e.target.value)} placeholder="Optional author"/></label><label>Status<select value={edit.status} onChange={e=>update('status',e.target.value)}><option>Draft</option><option>Published</option></select></label><label className="md:col-span-2">Short description<textarea rows="3" value={edit.description} onChange={e=>update('description',e.target.value)}/>{fields.description&&<small>{fields.description}</small>}</label>{edit.type==='Blogs'&&<label className="md:col-span-2">Blog content<textarea rows="10" value={edit.content} onChange={e=>update('content',e.target.value)} placeholder="Write the blog content here"/>{fields.content&&<small>{fields.content}</small>}</label>}<label className="md:col-span-2">{edit.type==='Videos'?'Video link':edit.type==='Webinars'?'Webinar link':'External link (optional)'}<input type="url" value={edit.url} onChange={e=>update('url',e.target.value)} placeholder="https://..."/>{fields.url&&<small>{fields.url}</small>}</label><label className="md:col-span-2">Cover image URL (optional)<input type="url" value={edit.image} onChange={e=>update('image',e.target.value)} placeholder="https://..."/>{fields.image&&<small>{fields.image}</small>}</label></div><div className="Properties-toggle-grid"><label className="Properties-check"><input type="checkbox" checked={edit.featured} onChange={e=>update('featured',e.target.checked)}/>Featured resource</label>{edit.type==='Webinars'&&<label className="Properties-check"><input type="checkbox" checked={edit.webinarStatus==='Upcoming'} onChange={e=>update('webinarStatus',e.target.checked?'Upcoming':'')}/>Upcoming webinar</label>}</div>{error&&<p className="Properties-error">{error}</p>}<button className="Properties-button" disabled={busy}>{busy?'Saving…':'Save Resource'}</button></form></section>;
  return <section className="admin-resource-page"><div className="Properties-admin-header"><div><p className="eyebrow">PRISM ADMIN</p><h1 className="title">Knowledge Center</h1><p>Manage blog posts, webinar links and video links shown on the Helpline page.</p></div><button className="Properties-button" onClick={()=>setEdit({...blank})}><Plus size={17}/>Add Resource</button></div>{loading?<p role="status">Loading resources…</p>:error?<p className="Properties-error">{error}</p>:!items.length?<div className="Properties-empty">No resources have been added yet.</div>:<div className="admin-resource-list">{items.map(item=><article key={item.id}><div><span>{item.type} · {item.status}</span><h2>{item.title}</h2><p>{item.description||'No description added.'}</p></div><div className="Properties-actions"><button className="Properties-button secondary" onClick={()=>setEdit(item)}>Edit</button>{item.url&&<a className="Properties-button secondary" href={item.url} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Open Link</a>}<button className="Properties-button Properties-danger" disabled={busy} onClick={()=>remove(item)}><Trash2 size={15}/>Delete</button></div></article>)}</div>}</section>;
}
